//! wasm-bindgen surface (spec 02 § wasm-bindgen surface).
//!
//! Exposes `seal()` / `open()` over `mosseal-core`. Compile-time config is
//! injected by the CLI builder (`mosseal build`, spec 05) through the
//! GENERATED `secrets.rs` file — see below.
//!
//! Secrets are obfuscated at compile time with `obfuse!` (AEAD-encrypted,
//! lazy-decrypted, zeroized-on-drop — replacing obfstr per D-decision).
//!
//! NOTE: there is deliberately NO `option_env!("MOSSEAL_EPOCHS")`
//! path here. `obfuse!` only accepts literals, so secrets cannot flow through
//! env vars at compile time; the generated `secrets.rs` is the single canonical
//! injection mechanism. The CLI builder writes it into the template copy it
//! compiles; the committed placeholder keeps dev/test builds compiling.

use mosseal_core::{
    binding,
    epoch::EpochRegistry,
    kdf::Argon2Profile,
    seal::{OpenOutput, SealContext, SealInput},
    time::{FetchTimes, TimeMode, TimeSource},
    MossealError,
};
use wasm_bindgen::prelude::*;

// `secrets.rs` is GENERATED by the CLI builder (`mosseal build`, spec 05).
// It must define exactly three items:
//
//   /// base64url 32-byte epoch secrets joined by `;` (epoch 0 first).
//   pub fn epochs_registry_str() -> String
//   /// comma-separated bare lowercase hostnames (spec 03).
//   pub fn allowed_domains_str() -> String
//   /// comma-separated https time-source URLs (spec 07; empty = defaults).
//   pub fn time_sources_str() -> String
//
// All wrap `obfuse!("...")` literals (obfuse only accepts literals, so
// env-injection must go through codegen). The committed placeholder returns
// empty strings so dev/test builds compile; `Mosseal::new` then fails loudly
// with a clean error rather than panicking. The builder overwrites this file
// in the template copy it compiles — a generated copy containing real secrets
// must NEVER be committed (see .gitignore exception strategy).
include!("secrets.rs");

/// Domains whitelist from the generated `secrets.rs`. Parsing lives in core so
/// it is natively testable and shared with the template build (spec 05).
fn whitelist() -> Vec<String> {
    binding::parse_domain_list(&allowed_domains_str())
}

/// Time sources from the generated `secrets.rs` (spec 07). Empty → the wasm
/// layer's `WebFetch` still receives the core defaults (an empty `Vec` in
/// `SealContext` makes `TimeResolver` fall back to `DEFAULT_TIME_SOURCES`).
fn time_sources() -> Vec<TimeSource> {
    mosseal_core::time::parse_time_sources(&time_sources_str()).unwrap_or_default()
}

/// Error taxonomy helper: JS sees a stable, machine-readable code (spec 02).
/// The `JsError` message is EXACTLY the code string (e.g. `BAD_PASSWORD`),
/// never the `thiserror` prose — the TS wrapper matches on it verbatim.
fn js_err(e: MossealError) -> JsError {
    JsError::new(e.code.as_str())
}

#[wasm_bindgen]
pub struct Mosseal {
    ctx: SealContext,
}

#[wasm_bindgen]
impl Mosseal {
    /// One-time init. Idempotent per page; concurrent `Mosseal.load` calls
    /// coalesce in the TS wrapper (spec 04).
    #[wasm_bindgen(constructor)]
    pub fn new() -> Result<Mosseal, JsError> {
        console_error_panic_hook::set_once();

        let registry = EpochRegistry::parse(&epochs_registry_str()).map_err(js_err)?;
        let wl = whitelist();
        binding::validate_whitelist(&wl).map_err(js_err)?;

        // Browser builds always bind runtime hostname (spec 03 § 2); the
        // Node/CLI path sets None (trusted), which the wrapper handles.
        let hostname = web_sys::window().and_then(|w| w.location().hostname().ok());

        Ok(Mosseal {
            ctx: SealContext {
                epochs: registry,
                whitelist: wl,
                argon_profile: Argon2Profile::from_build(),
                time_mode: TimeMode::from_build(),
                runtime_hostname: hostname,
                time_sources: time_sources(),
            },
        })
    }

    /// Seal into the fragment string (the part after `#ms=`).
    /// `data` is capped at [`mosseal_core::MAX_PAYLOAD_BYTES`] (v1, spec 01).
    #[wasm_bindgen]
    pub fn seal(
        &self,
        data: String,
        password: Option<String>,
        exp_secs: Option<f64>,
        kind: Option<u8>,
    ) -> Result<String, JsError> {
        let pw = password.filter(|p| !p.is_empty()).map(String::into_bytes);
        let input = SealInput {
            data: data.into_bytes(),
            kind: kind.unwrap_or(mosseal_core::envelope::kind::TOKEN),
            exp: exp_secs.filter(|e| *e > 0.0).map(|e| e as u64),
            password: pw,
            deterministic_salt: None,
            deterministic_nonce: None,
            deterministic_epoch: None,
        };
        self.ctx.seal(&input).map_err(js_err)
    }

    /// Open a fragment string; password required for password-flagged links.
    /// Async because expiry may fetch net time (spec 07).
    #[wasm_bindgen]
    pub async fn open(&self, link: String, password: Option<String>) -> Result<JsValue, JsError> {
        let pw = password.filter(|p| !p.is_empty()).map(String::into_bytes);
        let fetcher = WebFetch;
        let out: OpenOutput = self
            .ctx
            .open(&link, pw.as_deref(), &fetcher)
            .map_err(js_err)?;
        serde_wasm_bindgen::to_value(&OpenJs {
            data: String::from_utf8_lossy(&out.data).into_owned(),
            exp: out.exp,
            kind: out.kind,
        })
        .map_err(|e| JsError::new(&format!("serde: {e}")))
    }

    /// Conformance-only (spec 08): seal with injected salt/nonce/epoch so the
    /// Node/browser suites reproduce native vectors byte-exactly. `salt_hex`
    /// and `nonce_hex` are lowercase hex (32 / 24 chars). Never present in
    /// consumer builds (feature-gated).
    #[cfg(feature = "conformance")]
    #[wasm_bindgen(js_name = sealDeterministic)]
    pub fn seal_deterministic(
        &self,
        data: String,
        password: Option<String>,
        exp_secs: Option<f64>,
        kind: Option<u8>,
        salt_hex: String,
        nonce_hex: String,
        epoch: Option<u8>,
    ) -> Result<String, JsError> {
        let salt = parse_hex_arr::<16>(&salt_hex).map_err(|e| JsError::new(&e))?;
        let nonce = parse_hex_arr::<12>(&nonce_hex).map_err(|e| JsError::new(&e))?;
        let pw = password.filter(|p| !p.is_empty()).map(String::into_bytes);
        let input = SealInput {
            data: data.into_bytes(),
            kind: kind.unwrap_or(mosseal_core::envelope::kind::TOKEN),
            exp: exp_secs.filter(|e| *e > 0.0).map(|e| e as u64),
            password: pw,
            deterministic_salt: Some(salt),
            deterministic_nonce: Some(nonce),
            deterministic_epoch: epoch,
        };
        self.ctx.seal(&input).map_err(js_err)
    }

    /// Conformance-only (spec 08): open with a fixed net time so expiry
    /// vectors are reproducible without network access. Never present in
    /// consumer builds (feature-gated).
    #[cfg(feature = "conformance")]
    #[wasm_bindgen(js_name = openWithTime)]
    pub async fn open_with_time(
        &self,
        link: String,
        password: Option<String>,
        now_secs: f64,
    ) -> Result<JsValue, JsError> {
        let pw = password.filter(|p| !p.is_empty()).map(String::into_bytes);
        let fetcher = FixedFetch(now_secs);
        let out: OpenOutput = self
            .ctx
            .open(&link, pw.as_deref(), &fetcher)
            .map_err(js_err)?;
        serde_wasm_bindgen::to_value(&OpenJs {
            data: String::from_utf8_lossy(&out.data).into_owned(),
            exp: out.exp,
            kind: out.kind,
        })
        .map_err(|e| JsError::new(&format!("serde: {e}")))
    }
}

/// Decode a lowercase-hex string into a fixed-size byte array (conformance).
#[cfg(feature = "conformance")]
fn parse_hex_arr<const N: usize>(hex: &str) -> Result<[u8; N], String> {
    let bytes = hex::decode(hex).map_err(|e| format!("bad hex: {e}"))?;
    bytes
        .try_into()
        .map_err(|v: Vec<u8>| format!("expected {N} bytes, got {}", v.len()))
}

/// Fixed net-time fetcher for conformance open (spec 08).
#[cfg(feature = "conformance")]
struct FixedFetch(f64);

#[cfg(feature = "conformance")]
impl FetchTimes for FixedFetch {
    fn fetch_unix_secs(&self, _sources: &[TimeSource]) -> Option<f64> {
        Some(self.0)
    }

    fn system_now_secs(&self) -> f64 {
        // Deterministic: the mocked clock is also the cache timestamp.
        self.0
    }
}

#[derive(serde::Serialize)]
struct OpenJs {
    data: String,
    exp: u64,
    kind: u8,
}

/// wasm fetch strategy for time sources (spec 07): parallel fetches, first
/// success wins, overall timeout handled by the resolver budget.
struct WebFetch;

impl WebFetch {
    /// Call the JS bridge once and return the raw per-source bodies
    /// (order-stable; `None` for a failed source). Shared by both trait
    /// methods so a resolve performs a single network round-trip.
    fn fetch_bodies(sources: &[TimeSource]) -> Option<Vec<Option<String>>> {
        // The TS wrapper polyfills a sync bridge via `wasm-bindgen-rayon`-less
        // approach: fetch is async, so this sync trait is driven through a
        // JS-provided `mossealFetchTime` global registered by the wrapper.
        // (The TS wrapper always registers this before calling open().)
        let global = js_sys::global();
        let f = js_sys::Reflect::get(&global, &JsValue::from_str("mossealFetchTime")).ok()?;
        let f: js_sys::Function = f.dyn_into().ok()?;
        let urls: Vec<String> = sources.iter().map(|s| s.url.to_string()).collect();
        let res = f
            .call1(&JsValue::NULL, &serde_wasm_bindgen::to_value(&urls).ok()?)
            .ok()?;
        let res: Vec<serde_json::Value> = serde_wasm_bindgen::from_value(res).ok()?;
        Some(res.iter().map(|b| b.as_str().map(str::to_string)).collect())
    }
}

impl FetchTimes for WebFetch {
    fn fetch_unix_secs(&self, sources: &[TimeSource]) -> Option<f64> {
        // Failed sources yield `null` (spec 07: order-stable array, first
        // success wins across ALL sources) — skip them and keep trying, never
        // abort the loop. Selection lives in core (`time::first_valid_time`).
        let bodies = Self::fetch_bodies(sources)?;
        let refs: Vec<Option<&str>> = bodies.iter().map(|b| b.as_deref()).collect();
        mosseal_core::time::first_valid_time(sources, &refs)
    }

    fn fetch_all_unix_secs(&self, sources: &[TimeSource]) -> Vec<f64> {
        // Every reachable source's time, for strict-mode drift sanity
        // (spec 07 § optional v1.1).
        let Some(bodies) = Self::fetch_bodies(sources) else {
            return Vec::new();
        };
        let refs: Vec<Option<&str>> = bodies.iter().map(|b| b.as_deref()).collect();
        mosseal_core::time::all_valid_times(sources, &refs)
    }

    /// `std::time::SystemTime::now()` panics on wasm32-unknown-unknown, so the
    /// browser clock comes from `Date.now()` (spec 07 lenient fallback + cache).
    fn system_now_secs(&self) -> f64 {
        js_sys::Date::now() / 1000.0
    }
}

/// Register the JS-side time fetcher (spec 07): the TS wrapper installs a
/// global sync-bridge function backed by async fetch + Promise.any.
#[wasm_bindgen]
pub fn register_time_fetcher(fetch: js_sys::Function) {
    let global = js_sys::global();
    let _ = js_sys::Reflect::set(
        &global,
        &JsValue::from_str("mossealFetchTime"),
        &fetch.into(),
    );
}

// wasm-bindgen imports panic on non-wasm targets; gate tests to wasm32
// (run via `wasm-pack test --node`, spec 08).
//
// These cover the wasm-ONLY surface that cannot be reached natively: the
// generated-secrets parse path, the `JsError` code contract, and the
// conformance helpers. Cross-runtime byte-exactness is covered by the Node
// (vitest) and browser (Playwright) suites; core logic is unit-tested in
// `mosseal-core`.
#[cfg(target_arch = "wasm32")]
#[cfg(test)]
mod tests {
    use super::*;
    use wasm_bindgen_test::wasm_bindgen_test;

    /// Read the `.message` of a `JsError` (it is an `Error` object, not a
    /// string, so `as_string()` on the value itself returns `""`).
    fn js_error_message(err: JsError) -> String {
        let val: JsValue = err.into();
        js_sys::Reflect::get(&val, &JsValue::from_str("message"))
            .ok()
            .and_then(|m| m.as_string())
            .unwrap_or_default()
    }

    #[wasm_bindgen_test]
    fn init_fails_without_env() {
        // With the placeholder `secrets.rs`, the constructor must fail cleanly
        // rather than panic.
        let err = Mosseal::new()
            .err()
            .expect("placeholder secrets must fail init");
        // The JS-visible message is the stable machine-readable code (spec 02),
        // not the thiserror prose.
        let msg = js_error_message(err);
        assert!(
            matches!(
                msg.as_str(),
                "EPOCH_RETIRED" | "DOMAIN_MISMATCH" | "WASM_INIT_FAILED"
            ),
            "unexpected init error code: {msg:?}"
        );
    }

    #[wasm_bindgen_test]
    fn whitelist_is_empty_for_placeholder() {
        // Empty generated domains string → empty list (never `[""]`).
        assert!(whitelist().is_empty());
    }

    #[wasm_bindgen_test]
    fn time_sources_empty_for_placeholder() {
        // Placeholder returns "" → empty override → core uses the defaults.
        assert!(time_sources().is_empty());
    }

    #[wasm_bindgen_test]
    fn js_err_message_is_the_code_string() {
        // This is the contract `@mosseal/core`'s `fromWasmError` matches on
        // verbatim; the detail prose must NOT leak into the message.
        let e = MossealError::new(mosseal_core::ErrorCode::BadPassword, "prose detail");
        assert_eq!(js_error_message(js_err(e)), "BAD_PASSWORD");
    }

    #[cfg(feature = "conformance")]
    #[wasm_bindgen_test]
    fn parse_hex_arr_validates_hex_and_length() {
        assert_eq!(
            parse_hex_arr::<4>("deadbeef").unwrap(),
            [0xde, 0xad, 0xbe, 0xef]
        );
        assert!(parse_hex_arr::<4>("dead").is_err(), "wrong length");
        assert!(parse_hex_arr::<4>("zzzz").is_err(), "not hex");
    }

    #[cfg(feature = "conformance")]
    #[wasm_bindgen_test]
    fn fixed_fetch_returns_injected_time() {
        let f = FixedFetch(1234.0);
        assert_eq!(
            f.fetch_unix_secs(mosseal_core::time::DEFAULT_TIME_SOURCES),
            Some(1234.0)
        );
        // The mocked clock is also the cache timestamp (deterministic).
        assert_eq!(f.system_now_secs(), 1234.0);
    }
}
