// GENERATED by `mosseal build` (spec 05) — placeholder committed for dev/test
// builds only. The CLI builder overwrites this file with `obfuse!("...")`
// literals carrying the consumer's epoch secrets and domain whitelist.
// NEVER commit a generated copy containing real secrets (see .gitignore).
//
// The builder emits, e.g.:
//   pub fn epochs_registry_str() -> String {
//       obfuse::obfuse!("b64url-secret0;b64url-secret1").as_str().to_string()
//   }
//   pub fn allowed_domains_str() -> String {
//       obfuse::obfuse!("a.example.com,b.example.com").as_str().to_string()
//   }
//   pub fn time_sources_str() -> String {
//       obfuse::obfuse!("https://my-time.example/api").as_str().to_string()
//   }
//
// Epoch secrets are joined by `;`; an EMPTY entry is a RETIRED epoch (a hole),
// e.g. "secret0;;secret2" retires epoch 1 while epochs 0 and 2 keep their
// indices (spec 02 § Key epochs).
//
// NOTE: obfuse! only accepts string literals, which is why injection goes
// through this generated file rather than env vars.

/// Placeholder returning an empty registry so dev/test builds compile;
/// `Mosseal::new` then fails with a clean `EPOCH_RETIRED`-family error.
pub fn epochs_registry_str() -> String {
    String::new()
}

/// Placeholder returning an empty whitelist so dev/test builds compile;
/// `Mosseal::new` then fails with a clean `DOMAIN_MISMATCH`-family error.
pub fn allowed_domains_str() -> String {
    String::new()
}

/// Placeholder returning an empty time-source override (spec 07) so dev/test
/// builds compile; the core defaults are used instead.
pub fn time_sources_str() -> String {
    String::new()
}
