/**
 * Admin wasm loader (spec 05 § admin commands).
 *
 * `npx mosseal gen-secret|seal|open` runs the SAME crypto as the native
 * `mosseal-cli` binary via a precompiled wasm module shipped in this package
 * (`vendor/admin-wasm/`, built from `crates/mosseal-admin-wasm`). This module
 * loads that module and exposes a typed `Admin` handle.
 *
 * The artifact is a derived build output (not committed); it is regenerated by
 * `scripts/sync-admin-wasm.mjs` at `npm pack`/publish time and in CI. A missing
 * artifact yields an actionable error rather than a cryptic module-not-found.
 */
import { createRequire } from "node:module";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Package root. The bundled entry is `dist/mosseal.js`, so `import.meta.url`
 * points into `dist/`; the parent is the package root that holds `vendor/`.
 */
const PKG_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const VENDOR_GLUE = join(PKG_ROOT, "vendor", "admin-wasm", "mosseal_admin_wasm.cjs");

/** The wasm-bindgen `--target nodejs` glue surface we depend on. */
interface AdminWasmModule {
  Admin: new (epochs: string, domains: string) => AdminHandle;
}

interface AdminHandle {
  seal(
    data: string,
    password: string | null | undefined,
    expSecs: number | null | undefined,
    kind: number | null | undefined
  ): string;
  open(
    fragment: string,
    password: string | null | undefined,
    ignoreExpiry: boolean | null | undefined
  ): { data: string; exp: number; kind: number };
  free(): void;
}

/** Payload kind bytes (spec 01). */
export const KIND_TOKEN = 1;
export const KIND_BINARY_BLOB = 2;

let cached: AdminWasmModule | null = null;

/** Load (once) the vendored admin wasm glue. */
function loadModule(): AdminWasmModule {
  if (cached) return cached;
  if (!existsSync(VENDOR_GLUE)) {
    throw new Error(
      `admin wasm is missing at ${VENDOR_GLUE}.\n` +
        `  This is a derived build artifact. Reinstall @mosseal/cli, or in a ` +
        `source checkout run: node scripts/sync-admin-wasm.mjs`
    );
  }
  // The glue is CommonJS (`--target nodejs`); load it through createRequire so
  // the ESM bundle can consume it without a static import Vite would try to
  // inline. `import.meta.url` resolves inside `dist/` at runtime.
  const require = createRequire(import.meta.url);
  cached = require(VENDOR_GLUE) as AdminWasmModule;
  return cached;
}

/** A loaded admin context bound to a deployment's epochs + domain whitelist. */
export class Admin {
  private readonly handle: AdminHandle;

  private constructor(handle: AdminHandle) {
    this.handle = handle;
  }

  /**
   * Build an admin context.
   *
   * @param epochs  base64url 32-byte epoch secrets joined by `;` (epoch 0
   *   first; an empty entry is a retired hole). Same format as the native
   *   CLI's `--epochs` / `MOSSEAL_EPOCHS`.
   * @param domains comma-separated bare lowercase hostnames (spec 03). Same
   *   format as the native CLI's `--domains` / `MOSSEAL_ALLOWED_DOMAINS`.
   */
  static create(epochs: string, domains: string): Admin {
    const mod = loadModule();
    return new Admin(new mod.Admin(epochs, domains));
  }

  /** Seal `data` into a fragment string (the part after `#ms=`). */
  seal(
    data: string,
    opts: { password?: string; expSecs?: number; kind?: number } = {}
  ): string {
    return this.handle.seal(
      data,
      opts.password ?? null,
      opts.expSecs ?? null,
      opts.kind ?? KIND_TOKEN
    );
  }

  /** Open and verify a fragment; returns `{ data, exp, kind }`. */
  open(
    fragment: string,
    opts: { password?: string; ignoreExpiry?: boolean } = {}
  ): { data: string; exp: number; kind: number } {
    return this.handle.open(
      fragment,
      opts.password ?? null,
      opts.ignoreExpiry ?? false
    );
  }

  /** Release the underlying wasm object. */
  free(): void {
    this.handle.free();
  }
}
