/**
 * `secrets.rs` codegen (spec 05 § `mosseal build`, PLAN constraint 1).
 *
 * `obfuse!` only accepts string literals, so secrets cannot flow through
 * `option_env!` — the builder generates a Rust source file embedding the
 * consumer's epoch secrets and domain whitelist as obfuse-encrypted literals.
 *
 * The generated file is written into the TEMPLATE COPY the builder compiles,
 * never into the repo source (a generated copy containing real secrets must
 * never be committed — see .gitignore exception strategy).
 */
import type { ValidatedConfig } from "./env.js";

/**
 * Escape a string for embedding inside a Rust double-quoted string literal.
 *
 * Inputs are already validated (base64url secrets, `[a-z0-9.-]` hostnames),
 * so this is defense-in-depth: if codegen is ever called with unvalidated
 * input, a stray `"` or `\` must not break the literal or inject code.
 */
function rustStringLiteral(value: string): string {
  let out = "";
  for (const ch of value) {
    switch (ch) {
      case "\\":
        out += "\\\\";
        break;
      case '"':
        out += '\\"';
        break;
      case "\n":
        out += "\\n";
        break;
      case "\r":
        out += "\\r";
        break;
      case "\t":
        out += "\\t";
        break;
      default: {
        const code = ch.codePointAt(0)!;
        if (code < 0x20 || code === 0x7f) {
          out += `\\u{${code.toString(16)}}`;
        } else {
          out += ch;
        }
      }
    }
  }
  return out;
}

/**
 * Generate the contents of `secrets.rs`.
 */
export function generateSecretsRs(
  cfg: Pick<ValidatedConfig, "secrets" | "domains"> & {
    timeSources?: string[] | null;
  }
): string {
  // A `null` slot is a retired epoch → an empty entry in the `;`-joined
  // registry string. The Rust `EpochRegistry::parse` treats an empty entry as
  // a hole, so later epochs keep their index (spec 02 § Key epochs).
  const epochsJoined = rustStringLiteral(cfg.secrets.map((s) => s ?? "").join(";"));
  const domainsJoined = rustStringLiteral(cfg.domains.join(","));
  // Empty override = the wasm/template layer uses `time::DEFAULT_TIME_SOURCES`
  // (spec 07). Joined with `,` to match the env var's own list syntax.
  const timeSourcesJoined = rustStringLiteral((cfg.timeSources ?? []).join(","));
  return `// GENERATED by \`mosseal build\` (spec 05) — DO NOT COMMIT.
// This file contains obfuse-encrypted literals of the consumer's epoch
// secrets and domain whitelist. It is written into the template copy that
// wasm-pack compiles; it must never be checked into version control.
//
// obfuse! only accepts string literals, which is why injection goes through
// this generated file rather than env vars (PLAN constraint 1).
//
// Epoch secrets are joined by \`;\`; an EMPTY entry is a retired epoch (a
// hole) — later epochs keep their index so their links keep opening.

/// Base64url 32-byte epoch secrets joined by \`;\` (epoch 0 first; empty = retired).
pub fn epochs_registry_str() -> String {
    obfuse::obfuse!("${epochsJoined}").as_str().to_string()
}

/// Comma-separated bare lowercase hostnames (spec 03).
pub fn allowed_domains_str() -> String {
    obfuse::obfuse!("${domainsJoined}").as_str().to_string()
}

/// Comma-separated https time-source URLs (spec 07; empty = core defaults).
pub fn time_sources_str() -> String {
    obfuse::obfuse!("${timeSourcesJoined}").as_str().to_string()
}
`;
}

/**
 * Generate `mosseal-out/meta.json` contents (spec 05 § build flow step 4):
 * build provenance so apps can display it in devtools. Contains NO secrets.
 */
export function generateMetaJson(
  cfg: ValidatedConfig,
  fingerprint: string,
  version: string
): string {
  return (
    JSON.stringify(
      {
        generator: "mosseal",
        version,
        // Active (non-retired) epochs and total slots (incl. retired holes).
        epochs: cfg.secrets.filter((s) => s !== null).length,
        epochSlots: cfg.secrets.length,
        argonProfile: cfg.argonProfile,
        strictTime: cfg.strictTime,
        domains: cfg.domains,
        fingerprint,
      },
      null,
      2
    ) + "\n"
  );
}
